apiVersion: v1
kind: Pod
metadata:
  name: userprofile
  labels:
    app: userprofile
spec:
  containers:
    - name: userprofile
      image: registryoec4829.azurecr.io/userprofile:piotr
      ports:
      - containerPort: 80
      env:
      - name: SQL_USER
        value: sqladminoEc4829
      - name: SQL_PASSWORD
        value: 'Admin2021'
      - name: SQL_SERVER
        value: sqlserveroec4829.database.windows.net
      - name: SQL_DBNAME
        value: mydrivingDB
     
